# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-transfer-app
  labels:
    app: file-transfer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-transfer
  template:
    metadata:
      labels:
        app: file-transfer
    spec:
      containers:
      - name: file-transfer-app
        image: file-transfer-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: file-transfer-service
spec:
  selector:
    app: file-transfer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer